### PR TITLE
Add the examples with radiation module

### PR DESCRIPTION
**Pull request by wjge**

### CODE REVIEW

**Comment by marchdf** [comment]
You probably want to remove all those chk files...

**Comment by ldowen** [comment]
Yeah I'm inclined to agree. I'm not sure I want to have a big checkpoint file committed to the main branch. Especially since PeleMP is a submodule to other repos.

**Comment by wjge** [comment]
> You probably want to remove all those chk files...

Will remove eventually, there is no better way to share these chk files between different labs/teams for merging the code.

**Comment by drummerdoc** [comment]
Might want to be really careful with chk's as they stay in the repository forever (even after git removing them).

**Comment by wjge** [comment]
Close it for now.

**Pull request closed without merging**
